# Generated by Django 6.0.7 on 2026-07-23 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_fall_events(apps, schema_editor):
    # 구버전 POST가 남겼을 수 있는 동일 (guardian, room_name, room_number, occurred_at)
    # 중복 행을 제약 추가 전에 정리한다 — 가장 오래된 행(min id)만 남긴다
    FallEvent = apps.get_model("falls", "FallEvent")
    seen = set()
    for pk, guardian_id, room_name, room_number, occurred_at in (
        FallEvent.objects.values_list("id", "guardian_id", "room_name", "room_number", "occurred_at")
        .order_by("id")
    ):
        key = (guardian_id, room_name, room_number, occurred_at)
        if key in seen:
            FallEvent.objects.filter(pk=pk).delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('falls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder_phone', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fcm', 'fcm'), ('webpush', 'webpush')], max_length=10)),
                ('token', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['name', 'number'],
            },
        ),
        migrations.AlterField(
            model_name='fallevent',
            name='room_name',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(dedupe_fall_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='fallevent',
            constraint=models.UniqueConstraint(fields=('guardian', 'room_name', 'room_number', 'occurred_at'), name='uniq_fall_dedup'),
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('guardian', 'name', 'number'), name='uniq_room_per_guardian'),
        ),
    ]
