# Generated by Django 6.0.7 on 2026-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falls', '0002_guardianprofile_pushdevice_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushdevice',
            name='kind',
            field=models.CharField(choices=[('webpush', 'webpush')], max_length=10),
        ),
    ]
