-- 낙상 감지 백엔드 초기 스키마 — Django 모델 1:1 이식, 유니크 제약 이름을 여기서 고정한다
CREATE TABLE guardian (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(150) NOT NULL,
    password   VARCHAR(100) NOT NULL,          -- BCrypt 해시
    created_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uniq_guardian_username UNIQUE (username)
);

-- DRF authtoken 등가 — 보호자당 1개, 만료 없음
CREATE TABLE auth_token (
    key         VARCHAR(40) PRIMARY KEY,        -- 40자 hex 랜덤
    guardian_id BIGINT      NOT NULL REFERENCES guardian (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uniq_auth_token_guardian UNIQUE (guardian_id)
);

CREATE TABLE fall_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id     BIGINT           NOT NULL REFERENCES guardian (id) ON DELETE CASCADE,
    room_name       VARCHAR(20)      NOT NULL,  -- 방 문자열 스냅샷 (Room FK 아님 — 방을 지워도 기록 보존)
    room_number     SMALLINT         NOT NULL,
    occurred_at     TIMESTAMPTZ      NOT NULL,
    created_at      TIMESTAMPTZ      NOT NULL,
    confidence      DOUBLE PRECISION NOT NULL,
    acknowledged_at TIMESTAMPTZ,
    -- 오프라인 큐 재전송 멱등성의 근거 — 같은 낙상은 두 행이 될 수 없다
    CONSTRAINT uniq_fall_dedup UNIQUE (guardian_id, room_name, room_number, occurred_at)
);

CREATE TABLE room (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT      NOT NULL REFERENCES guardian (id) ON DELETE CASCADE,
    name        VARCHAR(20) NOT NULL,
    number      SMALLINT    NOT NULL,
    CONSTRAINT uniq_room_per_guardian UNIQUE (guardian_id, name, number)
);

CREATE TABLE guardian_profile (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT      NOT NULL REFERENCES guardian (id) ON DELETE CASCADE,
    elder_phone VARCHAR(20) NOT NULL DEFAULT '',
    CONSTRAINT uniq_guardian_profile_guardian UNIQUE (guardian_id)
);

CREATE TABLE push_device (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id BIGINT      NOT NULL REFERENCES guardian (id) ON DELETE CASCADE,
    kind        VARCHAR(10) NOT NULL,           -- "webpush"만 유효 (검증은 API 계층)
    token       TEXT        NOT NULL,           -- Web Push 구독 JSON 문자열
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uniq_push_device_token UNIQUE (token)
);
